#!/usr/bin/env bash
# Script to run nginx using nginx user
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i '1i user nginx;' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
