#!/usr/bin/env bash
# Script to run nginx using nginx user
sudo sed -i "s/\([ :]\)80 /\18080 /" /etc/nginx/sites-enabled/default
sudo pkill apache2
sudo chown -R nginx:nginx /etc/nginx/
sudo chmod u+rw /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
