#!/usr/bin/env bash
# Script to run nginx using nginx user
sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/www-data/nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
service nginx restart
