#!/usr/bin/env bash
# Script to run nginx using nginx user
pkill apache2
chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/www-data/nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
