#!/usr/bin/env bash
# install haproxy and load balancing

sudo apt-get update
sudo apt-get install haproxy -y

echo "
frontend http_front
    bind *:80
    mode http
    backend http_back

backend http_back
    balance roundrobbin
    server web-01 44.222.206.217 check
    server web-02 54.226.5.41 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart
